# Turn the curated candidate photos into square game tiles and emit the
# game's data file with full attribution.
#
# Curation is manual and deliberate: single dog, clearly visible, no
# identifiable human faces, no watermarks, no paintings, no group shots.
#
# Run:  powershell -ExecutionPolicy Bypass -File research\prepare-game-images.ps1

$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Drawing

$root    = Split-Path -Parent $PSScriptRoot
$srcBase = Join-Path $root 'research\game-candidates'
$outBase = Join-Path $root 'site\img\game'
$manifest = Get-Content (Join-Path $srcBase 'manifest.json') -Raw | ConvertFrom-Json

$TILE    = 620
$quality = 84

# index numbers refer to the per-breed contact sheets in research/
# Dropped after reviewing the tightened crop: candidates whose head no longer
# survives the square, or where the dog is too distant to judge. An unfair
# tile is worse than a hard one — the player should lose to the breed, not to
# the framing.
#   bergamasco 4, 10, 13  - fur texture only / distant dog in a field
#   oes 12                - torso, no head
#   schapendoes 8         - body only
$PICKS = [ordered]@{
    pon         = @(1, 3, 5, 6, 7, 8, 9, 10, 13, 15)
    bergamasco  = @(1, 3, 8, 9, 12)
    oes         = @(3, 4, 5, 8, 9, 10, 11, 13, 14)
    briard      = @(2, 4, 5, 10, 11, 12, 16)
    schapendoes = @(3, 6, 7, 10, 11, 13, 15, 16)
    beardie     = @(4, 6, 7, 8, 9, 10, 11, 12, 13, 14)
}

$codec  = [System.Drawing.Imaging.ImageCodecInfo]::GetImageEncoders() |
          Where-Object { $_.MimeType -eq 'image/jpeg' }
$params = New-Object System.Drawing.Imaging.EncoderParameters(1)
$params.Param[0] = New-Object System.Drawing.Imaging.EncoderParameter(
    [System.Drawing.Imaging.Encoder]::Quality, [long]$quality)

$emitted = @()

foreach ($breed in $PICKS.Keys) {
    $srcDir = Join-Path $srcBase $breed
    $outDir = Join-Path $outBase $breed
    New-Item -ItemType Directory -Path $outDir -Force | Out-Null

    $files = Get-ChildItem $srcDir -File |
             Where-Object { $_.Extension -match '^\.(jpg|jpeg|png)$' } |
             Sort-Object Name

    $n = 0
    foreach ($idx in $PICKS[$breed]) {
        if ($idx -lt 1 -or $idx -gt $files.Count) { Write-Warning "$breed #$idx out of range"; continue }
        $file = $files[$idx - 1]

        $meta = $manifest | Where-Object { $_.Breed -eq $breed -and $_.File -eq $file.Name } | Select-Object -First 1
        if (-not $meta) { Write-Warning "no manifest entry for $breed/$($file.Name)"; continue }

        $img = [System.Drawing.Image]::FromFile($file.FullName)

        # Tight centre square crop, biased up so heads survive.
        #
        # ZOOM matters for fairness, not looks: a loose crop leaves scenery in
        # frame, and players start learning "grass = PON" instead of learning
        # the dog. Cropping in pushes the animal to fill the tile so the
        # background stops being a tell.
        $ZOOM = 0.86
        $side = [int]([Math]::Min($img.Width, $img.Height) * $ZOOM)
        $sx   = [int](($img.Width  - $side) / 2)
        $sy   = [int](($img.Height - $side) * 0.32)

        $bmp = New-Object System.Drawing.Bitmap -ArgumentList @([int]$TILE, [int]$TILE)
        $g   = [System.Drawing.Graphics]::FromImage($bmp)
        $g.InterpolationMode = [System.Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic
        $g.PixelOffsetMode   = [System.Drawing.Drawing2D.PixelOffsetMode]::HighQuality
        $dest = New-Object System.Drawing.Rectangle -ArgumentList @(0, 0, [int]$TILE, [int]$TILE)
        $srcR = New-Object System.Drawing.Rectangle -ArgumentList @([int]$sx, [int]$sy, [int]$side, [int]$side)
        $g.DrawImage($img, $dest, $srcR, [System.Drawing.GraphicsUnit]::Pixel)
        $g.Dispose()

        $n++
        $name = "$n.jpg"
        $bmp.Save((Join-Path $outDir $name), $codec, $params)
        $bmp.Dispose()
        $img.Dispose()

        $emitted += [pscustomobject]@{
            breed      = $breed
            file       = "$breed/$name"
            author     = $meta.Author
            license    = $meta.License
            licenseUrl = $meta.LicenseUrl
            source     = $meta.Source
        }
    }
    Write-Host ("{0,-12} {1} tiles" -f $breed, $n)
}

# ---- emit site/game-data.js -------------------------------------------------

$lines = @()
$lines += '/*'
$lines += ' * Photo pool for the Spot the PON game.'
$lines += ' *'
$lines += ' * Generated by research/prepare-game-images.ps1 - do not hand edit.'
$lines += ' * Every tile carries the attribution its licence requires; the game'
$lines += ' * shows the credit for whichever photo is on screen.'
$lines += ' */'
$lines += ''
$lines += 'window.PON_GAME_PHOTOS = ['

foreach ($e in $emitted) {
    $author = $e.author -replace "'", "\'"
    $lic    = $e.license -replace "'", "\'"
    $lines += "  { breed: '$($e.breed)', file: '$($e.file)', author: '$author', license: '$lic', licenseUrl: '$($e.licenseUrl)', source: '$($e.source)' },"
}

$lines += ']'
$lines += ''

$dest = Join-Path $root 'site\game-data.js'
[System.IO.File]::WriteAllText($dest, ($lines -join "`r`n"), (New-Object System.Text.UTF8Encoding($false)))

Write-Host ''
Write-Host "Tiles in  $outBase"
Write-Host "Data file $dest  ($($emitted.Count) photos)"
